import util2 from "some-package/dist/utils.js";
const { util: smUtil, cliUtil } = util2;
import d from "http";
const { default: x, xx: yy, xxx } = d;
void util2;
void smUtil;
void cliUtil;
void d;
void x;
void yy;
void xxx;
